plugins:
  netconf:
    executor: central_deployment_agent
    source: https://github.com/cloudify-cosmo/cloudify-netconf-plugin/archive/0.2.1.zip
    package_name: cloudify-netconf-plugin
    package_version: '0.2.1'

data_types:

  netconf_target:
    properties:
      rfc6020@running:
        required: false
      # only for capability:
      # urn:ietf:params:netconf:capability:candidate:1.0
      rfc6020@candidate:
        required: false

  netconf_get_state:
    properties:
      rfc6020@source:
        type: netconf_target
        required: true
      rfc6020@filter:
        required: false

  netconf_get_config:
    properties:
      rfc6020@source:
        type: netconf_target
        required: true

  netconf_edit_config:
    properties:
      rfc6020@config:
        required: true
        default: {}
      rfc6020@target:
        type: netconf_target
        required: true
      rfc6020@error-option:
        required: false
        default: {}

  netconf_copy_config:
    properties:
      rfc6020@source:
        type: netconf_target
        required: true
      rfc6020@target:
        type: netconf_target
        required: true

  netconf_delete_config:
    properties:
      rfc6020@target:
        type: netconf_target
        required: true

  netconf_lock:
    properties:
      rfc6020@target:
        type: netconf_target
        required: true

  netconf_unlock:
    properties:
      rfc6020@target:
        type: netconf_target
        required: true

  netconf_close_session:
    # dont have any properties
    properties: {}

  netconf_kill_session:
    properties:
      session-id:
        required: true
        description: >
            replace to real session id that you recieved from lock operation
        type: integer
        default: 1

node_types:

  # common type for rpc calls
  cloudify.netconf.translator.xml2netconf:
    derived_from: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: netconf.cloudify_netconf.xml2netconf.run
          inputs: {}
        configure:
          implementation: netconf.cloudify_netconf.xml2netconf.run
          inputs: {}
        start:
          implementation: netconf.cloudify_netconf.xml2netconf.run
          inputs: {}
        stop:
          implementation: netconf.cloudify_netconf.xml2netconf.run
          inputs: {}
        delete:
          implementation: netconf.cloudify_netconf.xml2netconf.run
          inputs: {}


  # common type for rpc calls
  cloudify.netconf.nodes.xml_rpc:
    derived_from: cloudify.nodes.Root
    properties:
      # system fields common for everything
      netconf_auth:
        # login credentials for netconf server
        default:
          # netconf user
          user: ""
          # optional, netconf password
          password: ""
          # optional, netconf device ip
          ip: ""
          # optional, netconf user key
          key_content: ""
          # optional, netconf port
          port: 830
          # optional, save communication logs
          store_logs: false

      metadata:
        # list of namesapaces and capabilities
        default:
          xmlns:
           # try to use this value of namespace as default
            _: urn:ietf:params:xml:ns:netconf:base:1.0
          capabilities: {}

      # dont override it please
      base_xmlns:
        description: system xml namespaces
        default:
          rfc6020: urn:ietf:params:xml:ns:netconf:base:1.0

      # templates for rpc calls
      rfc6020@get:
        type: netconf_get_state

      rfc6020@get-config:
        type: netconf_get_config

      rfc6020@edit-config:
        type: netconf_edit_config

      rfc6020@copy-config:
        type: netconf_copy_config

      rfc6020@delete-config:
        type: netconf_delete_config

      rfc6020@lock:
        type: netconf_lock

      rfc6020@unlock:
        type: netconf_unlock

      rfc6020@close-session:
        type: netconf_close_session

      rfc6020@kill-session:
        type: netconf_kill_session

    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: netconf.cloudify_netconf.xml_rpc.run
          inputs: {}
        configure:
          implementation: netconf.cloudify_netconf.xml_rpc.run
          inputs: {}
        start:
          implementation: netconf.cloudify_netconf.xml_rpc.run
          inputs: {}
        stop:
          implementation: netconf.cloudify_netconf.xml_rpc.run
          inputs: {}
        delete:
          implementation: netconf.cloudify_netconf.xml_rpc.run
          inputs: {}
