plugins:
  netconf:
    executor: central_deployment_agent
    source: https://github.com/cloudify-cosmo/cloudify-netconf-plugin/archive/master.zip
    package_name: cloudify-netconf-plugin
    package_version: '0.1'

data_types:

  get_config:
    properties:
      source:
        required: true
        default:
          running: {}

  get_state:
    properties:
      source:
        required: true
        default:
          running: {}
      filter:
        required: false

node_types:

  # common type for rpc calls
  cloudify.netconf.nodes.xml_rpc:
    derived_from: cloudify.nodes.Root
    properties:
      netconf_auth:
        # login credentials for netconf server
        default:
          user: ""
          password: ""
          ip: ""
          key_content: ""

      metadata:
        # list of namesapaces and capabilities
        default:
          xmlns:
           # try to use this value of namespace as default
            _: urn:ietf:params:xml:ns:netconf:base:1.0
          capabilities: {}

      get-config:
        type: get_config

      get:
        type: get_state

    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: netconf.cloudify_netconf.xml_rpc.run
          inputs: {}
        configure:
          implementation: netconf.cloudify_netconf.xml_rpc.run
          inputs: {}
        start:
          implementation: netconf.cloudify_netconf.xml_rpc.run
          inputs: {}
        stop:
          implementation: netconf.cloudify_netconf.xml_rpc.run
          inputs: {}
        delete:
          implementation: netconf.cloudify_netconf.xml_rpc.run
          inputs: {}
