tosca_definitions_version: cloudify_dsl_1_3

imports:
  - http://www.getcloudify.org/spec/cloudify/3.4/types.yaml
  - https://raw.githubusercontent.com/cloudify-cosmo/cloudify-netconf-plugin/master/plugin.yaml

inputs:

  netconf_ip:
    type: string
    description: >
       netconf server ip
    default: 127.0.0.1

  netconf_user:
    type: string
    description: >
       netconf server user
    default: netconf
  netconf_password:
    type: string
    description: >
       netconf server user password
    default: netconf

  netconf_key_content:
    type: string
    description: >
       netconf server user rsa key content, can be used instead password
    default: ""

node_types:

  vyatta_node_config:
    derived_from: cloudify.netconf.nodes.xml_rpc
    properties:
      metadata:
        default:
          capabilities:
            - urn:ietf:params:netconf:base:1.0
            - urn:ietf:params:netconf:capability:writeable-running:1.0
            - urn:ietf:params:netconf:capability:rollback-on-error:1.0
            - urn:ietf:params:netconf:capability:startup:1.0
            - urn:ietf:params:netconf:capability:url:1.0
          xmlns:
            vyatta-if-v1: urn:vyatta.com:mgmt:vyatta-interfaces:1
            vyatta-interfaces-dataplane-v1: urn:vyatta.com:mgmt:vyatta-interfaces-dataplane:1
            vyatta-interfaces-loopback-v1: urn:vyatta.com:mgmt:vyatta-interfaces-loopback:1
            vyatta-protocols-static-v1: urn:vyatta.com:mgmt:vyatta-protocols-static:1
            vyatta-protocols-v1: urn:vyatta.com:mgmt:vyatta-protocols:1
            vyatta-service-https-v1: urn:vyatta.com:mgmt:vyatta-service-https:1
            vyatta-service-nat-v1: urn:vyatta.com:mgmt:vyatta-service-nat:1
            vyatta-service-netconf-v1: urn:vyatta.com:mgmt:vyatta-service-netconf:1
            vyatta-service-ssh-v1: urn:vyatta.com:mgmt:vyatta-service-ssh:1
            vyatta-services-v1: urn:vyatta.com:mgmt:vyatta-services:1
            vyatta-system-acm-configd-v1: urn:vyatta.com:mgmt:vyatta-system-acm-configd:1
            vyatta-system-acm-opd-v1: urn:vyatta.com:mgmt:vyatta-system-acm-opd:1
            vyatta-system-acm-v1: urn:vyatta.com:mgmt:vyatta-system-acm:1
            vyatta-system-login-v1: urn:vyatta.com:mgmt:vyatta-system-login:1
            vyatta-system-mgmt-v1: urn:vyatta.com:mgmt:vyatta-system-mgmt:1
            vyatta-system-misc-v1: urn:vyatta.com:mgmt:vyatta-system-misc:1
            vyatta-system-network-v1: urn:vyatta.com:mgmt:vyatta-system-network:1
            vyatta-system-package-v1: urn:vyatta.com:mgmt:vyatta-system-package:1
            vyatta-system-syslog-v1: urn:vyatta.com:mgmt:vyatta-system-syslog:1
            vyatta-system-v1: urn:vyatta.com:mgmt:vyatta-system:1

node_templates:

  vyatta_impl:
    type: vyatta_node_config
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          inputs:
            netconf_auth:
              user: { get_input: netconf_user }
              password: { get_input: netconf_password }
              ip: { get_input: netconf_ip }
              key_content: { get_input: netconf_key_content }
            calls:
              # get full config
              - action: rfc6020@get-config
                payload:
                  rfc6020@source:
                    rfc6020@running: {}
                save_to: origin_interfaces

outputs:
  config:
    description: Full config
    value:
        data: { get_attribute: [ vyatta_impl, origin_interfaces ] }
        ns: { get_attribute: [ vyatta_impl, origin_interfaces_ns ] }

